---

- name: Check if slurm is installed
  stat:
    path: "{{ var_slurm_install_dir }}"
  register: stat_result

- name: Create slurm IPA user "{{ slurm_user }}"
  ipa_user:
    ipa_host: "{{ freeipa_server }}"
    ipa_pass: "{{ var_freeipa_pass }}"
    givenname: "Slurm"
    sn: "User"
    uid: "{{ slurm_user }}"
    state: present

- name: Compile slurm 
  include_tasks: _slurm_compile.yml
  when: stat_result.stat.exists == False 
